import React from 'react'
import Image from 'next/image'
import Link from 'next/link'

export default function Project_section() {
    return (
      <div
        className={`min-h-screen w-full h-screen flex px-8 md:px-16 flex-col bg-gray-800`}
      >
        <section className="  my-8">
          <h2 className="text-red-400 text-2xl md:text-3xl">Projects</h2>
        </section>
        <section className="h-5/6 w-full">
          <div className=" md:w-1/4 w-full flex flex-col bg-white shadow-lg rounded-2xl">
            <section className="rounded-2xl ">
              <img className="rounded-2xl " src={"/img/projects/ascii.jpeg"} />
            </section>
            <section className="py-6 px-2">
              <h1 className="text-xl font-semibold mb-2">#ASCIIMEETSCOLORS</h1>
              <p>
                A set of image composites of photographs and ASCII characters
                generated by a python script.
              </p>
              <div className="mt-2">
                <h3 className="text-sm font-semibold">Visit the project:</h3>
                <a className="underline"
                  target="_blank"
                  href="https://opensea.io/collection/asciimeetscolors"
                >
                  OpenSea
                </a>
              </div>
            </section>
          </div>
        </section>
      </div>
    );
}
